apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-backend
  name: events-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: events-backend
  type: ClusterIP
