apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-frontend
  name: events-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: events-frontend
    spec:
      containers:
      - image: gcr.io/mar-roidtc313/frontend-dockerimage
        name: events-frontend
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://events-backend"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}